### ISSUE TITLE
Новый адрес ЛК

### ISSUE THREAD

**Issue by vladimirovii** [iamwildtuna/boxberry-sdk#1]
Boxberry для новых клиентов изменили адрес ЛК.
url от старого ЛК (https://api.boxberry.de), новый (http://account.boxberry.ru)

Вынесите возможность конфигурирования base_uri в Клиенте.

Также обратите внимание на вот эту ошибку
https://github.com/iamwildtuna/boxberry-sdk/blob/master/src/Client.php#L416

**Comment by iamwildtuna** [comment]
Здравствуйте, какой точный адрес нового API? Можете прислать свежую документацию?

**Comment by iamwildtuna** [comment]
Не актуально, нашел на сайте новый документ

**Comment by iamwildtuna** [comment]
Доработано в версии [0.6.2](https://github.com/iamwildtuna/boxberry-sdk/releases/tag/0.6.2)
