### ISSUE TITLE
метод deleteOrder

### ISSUE THREAD

**Issue by AntistressStore** [iamwildtuna/boxberry-sdk#10]
Сейчас работаю с Боксберри. В клиенте, 
метод deleteOrder
```
/**
     * Позволяет удалить заказ, который не проводился в акте
     *
     * @param string $order_id - ID заказа магазина или трекномер BB
     * @return boolean
     * @throws BoxBerryException
     */
    public function deleteOrder($order_id)
    {
        $response = $this->callApi('GET', 'ParselDel', ['ImId' => $order_id]);
        if (!empty($response['text']) && $response['text'] == 'ok') {
            return true;
        }

        return false;
    }
```
почему-то не находит заказов по айди интернет магазина, айди верный, пробовал преобразовывать и в строку, и числом передавать. Не находит. Зашел сейчас на [их справку](https://help.boxberry.ru/pages/viewpage.action?pageId=1704424). Не вижу метода **ParselDel** у них в документации и параметра (аргумента) ImId. Возможно они обновили api и поменяли метод на CancelOrder (Отзыв или удаление посылки)? В этом случае, если заменить метод ParselDel на CancelOrder, а параметр ImId на orderid по айдишнику ИМ находит и удаляет. Важно, что возвращает теперь не true, а false при успехе. Или где-то можно посмотреть справку по ParselDel

**Comment by iamwildtuna** [comment]
Изменили https://help.boxberry.ru/pages/viewpage.action?pageId=762957 тут видно, что с 1.10 добавился этот метод. Когад я писал SDK этой страницы еще не было, а в ЛК выли методы. Буду благодарен за Pull Request с справлением :)

**Comment by AntistressStore** [comment]
Хорошо, изменю, пошлю

**Comment by iamwildtuna** [comment]
Добавлено в [0.8.1](https://github.com/iamwildtuna/boxberry-sdk/releases/tag/0.8.1).
