### ISSUE TITLE
Как указать тип отправления доставки Почты России?

### ISSUE THREAD

**Issue by PankovAlxndr** [iamwildtuna/boxberry-sdk#2]
Здравствуйте, возможно ли указать тип отправления доставки Почты России?

![image](https://user-images.githubusercontent.com/3092550/66901541-906cd680-f007-11e9-86ad-1cfe22bfdcee.png)

**Comment by iamwildtuna** [comment]
Реализовал в версии [0.7.0](https://github.com/iamwildtuna/boxberry-sdk/releases/tag/0.7.0). Примеры в README.
