### ISSUE TITLE
Необходим вес при запросах

### ISSUE THREAD

**Issue by PankovAlxndr** [iamwildtuna/boxberry-sdk#4]
Делаю запрос на получения ПВЗ и получаю такую ошибку

От сервера BoxBerry при вызове метода DeliveryCosts получена ошибка: Необходимо указать вес отправления (200)

**Comment by iamwildtuna** [comment]
Здравствуйте. Пришлите лог запроса и ответа.

**Comment by iamwildtuna** [comment]
Смущает, что DeliveryCosts - это расчет тарифа, а не получение списка ПВЗ.

**Comment by PankovAlxndr** [comment]
`[WildTuna\BoxberrySdk\Exception\BoxBerryException] 
От сервера BoxBerry при вызове метода DeliveryCosts получена ошибка: Необходимо указать вес отправления (200)
/home/.../vendor/wildtuna/boxberry-sdk/src/Client.php:135
#0: WildTuna\BoxberrySdk\Client->callApi(string, string, array)
	/home/.../vendor/wildtuna/boxberry-sdk/src/Client.php:291
#1: WildTuna\BoxberrySdk\Client->calcTariff(object)
	/home/.../functions.php:438
#2: getRegionDaysBoxberry(string)
	/home/..../_create_order.php:312`

**Comment by iamwildtuna** [comment]
Вы вызываете `WildTuna\BoxberrySdk\Client->calcTariff(object)` - это расчет тарифа, а не список ПВЗ.

И еще это не логи запроса и ответа к API, а stack trace. Про логи запросов описано в разделе [Отладка](https://github.com/iamwildtuna/boxberry-sdk#debugging).

**Comment by PankovAlxndr** [comment]
Простите, не разобрался в спешке, в функции получения городов был расчет еще и времени со стоимостью, работало где-то 6 месяцев и сегодня резко перестало, оказалось что параметр "вес" при расчете стоимости теперь стал обязательным, а ранее такого требования не было.
