### ISSUE TITLE
Значение «Артикул товара» должно быть строкой

### ISSUE THREAD

**Issue by AntistressStore** [iamwildtuna/boxberry-sdk#7]
Здравствуйте. Спасибо большое за модуль! Облегчает интеграцию

 Если делать как в примере:
$item->setId(1);

От сервера BoxBerry при вызове метода ParselCreate получена ошибка: Значение «Артикул товара» должно быть строкой. №1. 200 {"err":"Значение «Артикул товара» должно быть строкой. №1."}

Получается метод должен принимать только строки:
$item->setId('erer'); // ID товара в БД ИМ'

Тогда все хорошо работает.

**Comment by iamwildtuna** [comment]
Спасибо, внесу правки

**Comment by iamwildtuna** [comment]
Исправлено в [0.8.6](https://github.com/iamwildtuna/boxberry-sdk/releases/tag/0.8.6).
