### ISSUE TITLE
Получить код города по Индексу

### ISSUE THREAD

**Issue by AntistressStore** [iamwildtuna/boxberry-sdk#8]
Здравствуйте. Подскажите, **как получить код города по индексу почтовому**? Есть такая возможность в api? Обыскал все справочники. **Как ограничить результат только одним городом**, и получить код города по боксберри только для него. Методы ListCitiesFull,ListCities, можно ограничить только страной, они выдают большого размера json, а нужен определенный город. А ListPoints,ListPointsShort требуют код города по базе боксберри.

**Comment by iamwildtuna** [comment]
В API boxberry такого не видел. У dadata есть [https://dadata.ru/api/delivery/](функция), которая, возможно, поможет.

**Comment by AntistressStore** [comment]
> В API boxberry такого не видел. У dadata есть [https://dadata.ru/api/delivery/](%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D1%8F), которая, возможно, поможет.

Спасибо! Как раз им сейчас и пользуюсь.

**Comment by fazer** [comment]
Спасибо за API dadata. Попробую их использовать. Сейчас мы храним у себя справочник городов и там же id города в каждой службе доставки. Отдельные импорты этих данных на кроне для каждой службы доставки :)
