### ISSUE TITLE
добавил (модернизировал) тарификатор

### ISSUE THREAD

**Issue by AntistressStore** [iamwildtuna/boxberry-sdk#9]
Здравствуйте. Для своих нужд добавил (модернизировал) тарификатор (бесплатный, без авторизации) на версию V2. Добавил возможность за один запрос получать стоимость и +сроки. Делал через extends новых классов (пример, CalculateInfoV extends CalculateInfo) включение в оригинальные файлы не должно занять много времени. Могу поделиться с проектом, если в этом есть интерес. Но не знаю каким образом это сделать. Сюда прикрепить в сообщении?

**Comment by AntistressStore** [comment]
Извиняюсь, перепутал проект. Речь идет о вашем проекте для Почты России.

**Comment by iamwildtuna** [comment]
Здравствуйте. Что за API V2?

**Comment by AntistressStore** [comment]
которое находится по адресу https://delivery.pochta.ru/**v2**/calculate/tariff/delivery

**Comment by iamwildtuna** [comment]
Первый раз вижу такой сервис. Он очень похож на https://tariff.pochta.ru/#/ с который [уже есть](https://github.com/lapaygroup/RussianPost#tariffs) интеграция с SDK

**Comment by iamwildtuna** [comment]
А, понятно. Они переделали [API расчетов доставки](https://github.com/lapaygroup/RussianPost#%D1%80%D0%B0%D1%81%D1%87%D0%B5%D1%82-%D1%81%D1%80%D0%BE%D0%BA%D0%BE%D0%B2-%D0%B4%D0%BE%D1%81%D1%82%D0%B0%D0%B2%D0%BA%D0%B8)

**Comment by AntistressStore** [comment]
я про этот ваш сервис и пишу, ошибся с форумом. Там идут запросы на v1 в тарификаторе. Он возвращает только стоимость доставки. Я изменил его, теперь корректно работает и с v2

**Comment by iamwildtuna** [comment]
Формат сильно изменился? Что-то не вижу в v2 где сроки доставки возвращаются. Можете прислать строку-пример расчета из их UI?

**Comment by AntistressStore** [comment]
Отправил вам на почту
